Update publish.servicenow.plugin.yml

diff --git a/.github/workflows/publish.servicenow.plugin.yml b/.github/workflows/publish.servicenow.plugin.yml
--- a/.github/workflows/publish.servicenow.plugin.yml
+++ b/.github/workflows/publish.servicenow.plugin.yml
@@ -102,7 +102,7 @@ jobs:
               echo "JAR src path: ${srcjarpath} JAR destination: ${dstjarpath}"
               ls -la ${srcjarpath}
               ls -la ${releasedir}
-              mv ${srcjarpath} ${dstjarpath} || echo "File Copy Failed!"; exit 2
+              mv ${srcjarpath} ${dstjarpath} || { echo "File Copy Failed!" && exit 2 }
             fi
           done
           EOF
