Fix servicenow plugin gha (#531)
* Update publish.servicenow.plugin.yml

diff --git a/.github/workflows/publish.servicenow.plugin.yml b/.github/workflows/publish.servicenow.plugin.yml
--- a/.github/workflows/publish.servicenow.plugin.yml
+++ b/.github/workflows/publish.servicenow.plugin.yml
@@ -99,7 +99,10 @@ jobs:
               fi
               
               dstjarpath=${releasedir}/${buildname}-${version}-${buildversion}.jar
-              mv ${srcjarpath} ${dstjarpath} || echo "File Copy Failed!"; exit 1
+              echo "JAR src path: ${srcjarpath} JAR destination: ${dstjarpath}"
+              ls -la ${srcjarpath}
+              ls -la ${releasedir}
+              mv ${srcjarpath} ${dstjarpath} || { echo "File Copy Failed!" && exit 2; }
             fi
           done
           EOF
